"""tasks

Revision ID: 510b9300c8d5
Revises: c363b55b2938
Create Date: 2024-01-27 21:04:40.852679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510b9300c8d5'
down_revision = 'c363b55b2938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('weight_user', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
