"""empty message

Revision ID: 95695c00f188
Revises: 7b0b7434e9e3
Create Date: 2024-01-28 10:45:51.623331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95695c00f188'
down_revision = '7b0b7434e9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tasks_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
