"""empty message

Revision ID: dce476d4275c
Revises: d70869f8e5b6
Create Date: 2024-01-28 06:27:31.667238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce476d4275c'
down_revision = 'd70869f8e5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('upcoming', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_upcoming'), ['upcoming'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_upcoming'))
        batch_op.drop_index(batch_op.f('ix_user_severity'))
        batch_op.drop_column('upcoming')
        batch_op.drop_column('severity')

    # ### end Alembic commands ###
