"""empty message

Revision ID: ff874ec03ce1
Revises: 448a5687537b
Create Date: 2024-01-28 06:29:29.933223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff874ec03ce1'
down_revision = '448a5687537b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upcoming', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_upcoming'), ['upcoming'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_upcoming'))
        batch_op.drop_column('upcoming')

    # ### end Alembic commands ###
